#!/bin/sh

###
### このスクリプトを流しこめば、ある程度インストール作業を肩代わりしてくれます.
###

create_configuration() {
  echo -n '[n]'
  read install

  if [ -z "$install" ] || [ $install = 'n' ] ; then
    # Do nothing
    return
  elif [ $install = 'y' ] ; then
    # Backup
    if [ -e $(cd $(dirname $0);pwd)/config.pl ] ; then
      mv $(cd $(dirname $0);pwd)/config.pl $(cd $(dirname $0);pwd)/config.pl.bak
    fi

    # Create
    cp $(cd $(dirname $0);pwd)/config.pl.sample $(cd $(dirname $0);pwd)/config.pl
    echo 'config.pl を作成しました.'
    return
  fi

  echo 'y かn を指定して下さい．'
  create_configuration
}

echo '依存モジュールをインストールします.'
cpanm --installdeps -n $(cd $(dirname $0);pwd)
$(cd $(dirname $0);pwd)/script/install_DBD.sh

cat << MSG

config.pl を作成しますか？[y/n]
MSG
create_configuration

cat << MSG

!!! 以下は手動で行う必要があります !!!

次にDB のセットアップを行ってください.
データベースを用意し（現在はMySQL、SQLiteに対応）、db/init.sql（init_sqlite.sql）を用いて初期化を行って下さい.

DB の設定が完了したら、コピーしたconfig.pl に設定を記述してください.
('database' の設定は最低限行わないと動きません)
MSG
